"""
Comprehensive tests for Aero Agent RAG system.

Tests cover:
- Document reading (multiple formats)
- Text preprocessing
- Document chunking
- Embeddings (hash fallback)
- Vector storage (DuckDB, SQLite, in-memory)
- Search functionality
- Metadata management
"""

import tempfile
from pathlib import Path
import pytest
import numpy as np


# =============================================================================
# Test Fixtures
# =============================================================================


@pytest.fixture
def sample_text():
    """Sample text for testing."""
    return """
    Introduction to Aerodynamics

    Aerodynamics is a branch of physics that deals with the motion of air
    and other gaseous fluids and with the forces acting on bodies in motion
    relative to such fluids.

    The fundamental equations governing aerodynamic flow are the Navier-Stokes
    equations, which describe the motion of viscous fluid substances.

    Key concepts include:
    - Lift: The force perpendicular to the flow direction
    - Drag: The force parallel to the flow direction
    - Pressure distribution: How pressure varies around a body

    For incompressible flow, the continuity equation states that:
    $\\nabla \\cdot \\mathbf{u} = 0$

    And the momentum equation becomes:
    $\\frac{\\partial \\mathbf{u}}{\\partial t} + (\\mathbf{u} \\cdot \\nabla)\\mathbf{u}
    = -\\frac{1}{\\rho}\\nabla p + \\nu \\nabla^2 \\mathbf{u}$
    """


@pytest.fixture
def temp_dir():
    """Create a temporary directory for tests."""
    with tempfile.TemporaryDirectory() as tmpdir:
        yield Path(tmpdir)


@pytest.fixture
def sample_chunks():
    """Sample chunks for testing."""
    return [
        "Aerodynamics is the study of air flow around objects.",
        "Lift is generated by pressure differences on wing surfaces.",
        "Drag is the resistance force opposing motion through air.",
        "The Navier-Stokes equations govern fluid dynamics.",
        "Reynolds number determines flow regime: laminar or turbulent.",
    ]


# =============================================================================
# Preprocessor Tests
# =============================================================================


class TestTextPreprocessor:
    """Tests for text preprocessing."""

    def test_basic_preprocess(self, sample_text):
        """Test basic text preprocessing."""
        from aero.rag.preprocess import TextPreprocessor

        preprocessor = TextPreprocessor()
        result = preprocessor.preprocess(sample_text)

        assert result.text is not None
        assert len(result.text) > 0
        # Should have extracted equations
        assert len(result.equations) > 0

    def test_whitespace_normalization(self):
        """Test whitespace normalization."""
        from aero.rag.preprocess import TextPreprocessor

        preprocessor = TextPreprocessor()
        text = "Hello   world\t\ttest\n\n\n\nmultiple"
        result = preprocessor.preprocess(text)

        # Should not have multiple consecutive spaces
        assert "   " not in result.text
        # Should not have more than 2 newlines
        assert "\n\n\n" not in result.text

    def test_boilerplate_removal(self):
        """Test boilerplate removal."""
        from aero.rag.preprocess import TextPreprocessor

        preprocessor = TextPreprocessor(remove_boilerplate=True)
        text = "Main content here.\nPage 1 of 10\nCopyright 2024 Test Corp"
        result = preprocessor.preprocess(text)

        assert "Page 1 of 10" not in result.text
        assert "Copyright" not in result.text
        assert "Main content" in result.text

    def test_equation_extraction(self):
        """Test LaTeX equation extraction."""
        from aero.rag.preprocess import TextPreprocessor

        preprocessor = TextPreprocessor(extract_equations=True)
        text = "The formula is $E = mc^2$ and also $$F = ma$$"
        result = preprocessor.preprocess(text)

        assert len(result.equations) >= 2

    def test_clean_for_embedding(self, sample_text):
        """Test cleaning text for embedding."""
        from aero.rag.preprocess import TextPreprocessor

        preprocessor = TextPreprocessor()
        result = preprocessor.preprocess(sample_text)
        cleaned = preprocessor.clean_for_embedding(result.text)

        assert len(cleaned) > 0
        # Should remove equation placeholders
        assert "[EQUATION]" not in cleaned


# =============================================================================
# Chunker Tests
# =============================================================================


class TestTextChunker:
    """Tests for document chunking."""

    def test_basic_chunking(self, sample_text):
        """Test basic text chunking."""
        from aero.rag.chunker import TextChunker

        chunker = TextChunker(chunk_size=200, overlap=40)
        chunks = chunker.chunk(sample_text)

        assert len(chunks) > 1
        for chunk in chunks:
            # Each chunk should be reasonable size
            assert len(chunk) <= 300  # Some flexibility for word boundaries

    def test_chunk_overlap(self):
        """Test that chunks have proper overlap."""
        from aero.rag.chunker import TextChunker

        text = "A " * 100 + "B " * 100 + "C " * 100
        chunker = TextChunker(chunk_size=100, overlap=20)
        chunks = chunker.chunk(text)

        assert len(chunks) >= 2

    def test_empty_text(self):
        """Test chunking empty text."""
        from aero.rag.chunker import TextChunker

        chunker = TextChunker()
        chunks = chunker.chunk("")

        assert chunks == []

    def test_short_text(self):
        """Test chunking text shorter than chunk size."""
        from aero.rag.chunker import TextChunker

        chunker = TextChunker(chunk_size=1000)
        chunks = chunker.chunk("Short text")

        assert len(chunks) == 1
        assert chunks[0] == "Short text"

    def test_section_based_chunking(self, sample_text):
        """Test chunking with section detection."""
        from aero.rag.chunker import TextChunker

        chunker = TextChunker(chunk_size=200, respect_sections=True)
        chunks = chunker.chunk(sample_text)

        assert len(chunks) > 0


# =============================================================================
# Embedder Tests
# =============================================================================


class TestEmbedder:
    """Tests for embedding generation."""

    def test_hash_embedder(self):
        """Test hash-based embedder."""
        from aero.rag.embedder import HashEmbedder

        embedder = HashEmbedder(dimension=384)

        text = "Test embedding text"
        embedding = embedder.embed(text)

        assert isinstance(embedding, np.ndarray)
        assert embedding.shape == (384,)
        # Should be normalized
        assert abs(np.linalg.norm(embedding) - 1.0) < 0.01

    def test_hash_embedder_deterministic(self):
        """Test that hash embedder is deterministic."""
        from aero.rag.embedder import HashEmbedder

        embedder = HashEmbedder(dimension=384)

        text = "Same text"
        emb1 = embedder.embed(text)
        emb2 = embedder.embed(text)

        np.testing.assert_array_almost_equal(emb1, emb2)

    def test_hash_embedder_different_texts(self):
        """Test that different texts produce different embeddings."""
        from aero.rag.embedder import HashEmbedder

        embedder = HashEmbedder(dimension=384)

        emb1 = embedder.embed("First text")
        emb2 = embedder.embed("Second text completely different")

        # Should not be identical
        assert not np.allclose(emb1, emb2)

    def test_hash_embedder_similarity(self):
        """Test similarity calculation."""
        from aero.rag.embedder import HashEmbedder

        embedder = HashEmbedder(dimension=384)

        # Same text should have similarity 1.0
        sim = embedder.similarity("test", "test")
        assert abs(sim - 1.0) < 0.01

    def test_embed_batch(self):
        """Test batch embedding."""
        from aero.rag.embedder import HashEmbedder

        embedder = HashEmbedder(dimension=384)

        texts = ["First", "Second", "Third"]
        embeddings = embedder.embed_batch(texts)

        assert len(embeddings) == 3
        for emb in embeddings:
            assert isinstance(emb, np.ndarray)
            assert emb.shape == (384,)

    def test_auto_embedder(self):
        """Test auto embedder fallback."""
        from aero.rag.embedder import AutoEmbedder

        embedder = AutoEmbedder()

        # Should work even without Ollama or SentenceTransformers
        embedding = embedder.embed("Test text")

        assert isinstance(embedding, np.ndarray)
        assert len(embedding) > 0


# =============================================================================
# Vector Store Tests
# =============================================================================


class TestInMemoryVectorStore:
    """Tests for in-memory vector store."""

    def test_add_document(self, sample_chunks):
        """Test adding documents."""
        from aero.rag.store import InMemoryVectorStore
        from aero.rag.embedder import HashEmbedder

        store = InMemoryVectorStore()
        embedder = HashEmbedder()

        chunks = [
            {"content": c, "embedding": embedder.embed(c).tolist()}
            for c in sample_chunks
        ]

        doc_id = store.add_document(
            content="Full document content",
            metadata={"source": "test"},
            chunks=chunks,
        )

        assert doc_id is not None
        assert store.count() == 1

    def test_search(self, sample_chunks):
        """Test vector search."""
        from aero.rag.store import InMemoryVectorStore
        from aero.rag.embedder import HashEmbedder

        store = InMemoryVectorStore()
        embedder = HashEmbedder()

        # Add document with chunks
        chunks = [
            {"content": c, "embedding": embedder.embed(c).tolist()}
            for c in sample_chunks
        ]
        store.add_document(content="Document about aerodynamics", chunks=chunks)

        # Search
        query_emb = embedder.embed("aerodynamics air flow")
        results = store.search(query_embedding=query_emb, top_k=3)

        assert len(results) <= 3
        for result in results:
            assert result.score >= 0
            assert result.chunk is not None

    def test_delete_document(self, sample_chunks):
        """Test document deletion."""
        from aero.rag.store import InMemoryVectorStore
        from aero.rag.embedder import HashEmbedder

        store = InMemoryVectorStore()
        embedder = HashEmbedder()

        chunks = [{"content": c, "embedding": embedder.embed(c).tolist()} for c in sample_chunks]
        doc_id = store.add_document(content="Test", chunks=chunks)

        assert store.count() == 1
        assert store.delete_document(doc_id) is True
        assert store.count() == 0


class TestSQLiteVectorStore:
    """Tests for SQLite vector store."""

    def test_create_store(self, temp_dir):
        """Test creating SQLite store."""
        from aero.rag.store import SQLiteVectorStore

        db_path = str(temp_dir / "test.db")
        store = SQLiteVectorStore(db_path=db_path)

        assert store.count() == 0
        store.close()

    def test_persistence(self, temp_dir, sample_chunks):
        """Test data persistence."""
        from aero.rag.store import SQLiteVectorStore
        from aero.rag.embedder import HashEmbedder

        db_path = str(temp_dir / "test.db")
        embedder = HashEmbedder()

        # Add data
        store = SQLiteVectorStore(db_path=db_path)
        chunks = [{"content": c, "embedding": embedder.embed(c).tolist()} for c in sample_chunks]
        store.add_document(content="Persistent doc", chunks=chunks)
        store.close()

        # Reopen and verify
        store2 = SQLiteVectorStore(db_path=db_path)
        assert store2.count() == 1
        store2.close()


class TestDuckDBVectorStore:
    """Tests for DuckDB vector store."""

    def test_create_store(self, temp_dir):
        """Test creating DuckDB store."""
        try:
            from aero.rag.store import DuckDBVectorStore

            db_path = str(temp_dir / "test.duckdb")
            store = DuckDBVectorStore(db_path=db_path)

            assert store.count() == 0
            store.close()
        except RuntimeError:
            pytest.skip("DuckDB not available")

    def test_add_and_search(self, temp_dir, sample_chunks):
        """Test adding and searching in DuckDB."""
        try:
            from aero.rag.store import DuckDBVectorStore
            from aero.rag.embedder import HashEmbedder

            db_path = str(temp_dir / "test.duckdb")
            store = DuckDBVectorStore(db_path=db_path)
            embedder = HashEmbedder()

            chunks = [{"content": c, "embedding": embedder.embed(c).tolist()} for c in sample_chunks]
            store.add_document(content="Test doc", metadata={"type": "test"}, chunks=chunks)

            query_emb = embedder.embed("aerodynamics")
            results = store.search(query_embedding=query_emb, top_k=3)

            assert len(results) > 0
            store.close()
        except RuntimeError:
            pytest.skip("DuckDB not available")


class TestVectorStoreFactory:
    """Tests for vector store factory."""

    def test_create_auto(self, temp_dir):
        """Test auto store creation."""
        from aero.rag.store import create_vector_store

        db_path = str(temp_dir / "auto.db")
        store = create_vector_store(db_path=db_path)

        assert store is not None
        assert store.count() == 0


# =============================================================================
# Document Reader Tests
# =============================================================================


class TestDocumentReader:
    """Tests for document reading."""

    def test_read_text_file(self, temp_dir):
        """Test reading text files."""
        from aero.rag.reader import DocumentReader

        # Create test file
        test_file = temp_dir / "test.txt"
        test_file.write_text("Hello, this is a test document.")

        reader = DocumentReader()
        doc = reader.read(test_file)

        assert doc.content == "Hello, this is a test document."
        assert doc.format == ".txt"

    def test_read_markdown(self, temp_dir):
        """Test reading markdown files."""
        from aero.rag.reader import DocumentReader

        test_file = temp_dir / "test.md"
        test_file.write_text("# Title\n\nSome content here.")

        reader = DocumentReader()
        doc = reader.read(test_file)

        assert "Title" in doc.content
        assert doc.format == ".md"

    def test_unsupported_format(self, temp_dir):
        """Test unsupported file format."""
        from aero.rag.reader import DocumentReader

        test_file = temp_dir / "test.xyz"
        test_file.write_text("content")

        reader = DocumentReader()

        with pytest.raises(ValueError, match="Unsupported"):
            reader.read(test_file)

    def test_supported_formats(self):
        """Test listing supported formats."""
        from aero.rag.reader import DocumentReader

        reader = DocumentReader()
        formats = reader.supported_formats()

        assert ".txt" in formats
        assert ".md" in formats
        assert ".pdf" in formats


# =============================================================================
# Metadata Store Tests
# =============================================================================


class TestMetadataStore:
    """Tests for metadata storage."""

    def test_sqlite_store(self, temp_dir):
        """Test SQLite metadata store."""
        from aero.rag.metadata import SQLiteMetadataStore

        db_path = str(temp_dir / "meta.db")
        store = SQLiteMetadataStore(db_path)

        # Test document operations
        doc_id = store.add_document(
            path="/test/doc.pdf",
            title="Test Document",
            tags=["test", "example"],
            metadata={"author": "Test"},
        )

        assert doc_id is not None

        # Retrieve
        doc = store.get_document(doc_id)
        assert doc is not None
        assert doc["title"] == "Test Document"

        store.close()

    def test_chunk_operations(self, temp_dir):
        """Test chunk operations."""
        from aero.rag.metadata import SQLiteMetadataStore
        import numpy as np

        db_path = str(temp_dir / "meta.db")
        store = SQLiteMetadataStore(db_path)

        doc_id = store.add_document(path="/test.txt", title="Test")

        # Add chunk
        embedding = np.random.randn(384).astype(np.float32)
        chunk_id = store.add_chunk(
            document_id=doc_id,
            chunk_index=0,
            text="Chunk content",
            embedding=embedding,
        )

        assert chunk_id is not None

        # Get chunks
        chunks = store.get_chunks(doc_id)
        assert len(chunks) == 1

        store.close()


# =============================================================================
# Integration Tests
# =============================================================================


class TestRAGIntegration:
    """Integration tests for the full RAG pipeline."""

    def test_full_pipeline(self, temp_dir, sample_text):
        """Test complete RAG pipeline."""
        from aero.rag.store import create_vector_store
        from aero.rag.embedder import HashEmbedder
        from aero.rag.chunker import TextChunker
        from aero.rag.preprocess import TextPreprocessor

        # Initialize components
        store = create_vector_store(str(temp_dir / "rag.db"))
        embedder = HashEmbedder()
        chunker = TextChunker(chunk_size=200, overlap=40)
        preprocessor = TextPreprocessor()

        # Process document
        processed = preprocessor.preprocess(sample_text)
        cleaned = preprocessor.clean_for_embedding(processed.text)
        chunks = chunker.chunk(cleaned)

        # Create chunk data with embeddings
        chunk_data = [
            {"content": c, "embedding": embedder.embed(c).tolist(), "metadata": {"idx": i}}
            for i, c in enumerate(chunks)
        ]

        # Add to store
        doc_id = store.add_document(
            content=sample_text,
            metadata={"source": "test", "equations": len(processed.equations)},
            chunks=chunk_data,
        )

        assert doc_id is not None
        assert store.count() == 1

        # Search
        query = "Navier-Stokes equations fluid dynamics"
        query_emb = embedder.embed(query)
        results = store.search(query_emb, top_k=3)

        assert len(results) > 0
        # Top result should be relevant
        assert results[0].score > 0

    def test_multiple_documents(self, temp_dir):
        """Test handling multiple documents."""
        from aero.rag.store import create_vector_store
        from aero.rag.embedder import HashEmbedder

        store = create_vector_store(str(temp_dir / "multi.db"))
        embedder = HashEmbedder()

        docs = [
            "Aerodynamics studies air flow around objects like aircraft.",
            "Machine learning uses algorithms to learn patterns from data.",
            "Climate change affects global weather patterns significantly.",
        ]

        for i, content in enumerate(docs):
            chunks = [{"content": content, "embedding": embedder.embed(content).tolist()}]
            store.add_document(content=content, metadata={"doc_num": i}, chunks=chunks)

        assert store.count() == 3

        # Search should find most relevant
        query_emb = embedder.embed("aircraft aerodynamics")
        results = store.search(query_emb, top_k=2)

        assert len(results) == 2
        # First result should be about aerodynamics
        assert "aerodynamics" in results[0].chunk.content.lower() or "air" in results[0].chunk.content.lower()


# =============================================================================
# Run Tests
# =============================================================================


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
